### ISSUE TITLE
CRS / SRS updates, any?

### ISSUE THREAD

**Issue by karunakar2** [cf-json/cf-json.github.io#16]
Hello team,
CF-JSON is a wonderful way of communicating Met Ocean data sets and i started implementing it.
I am wondering if there would be any update on the reference coordinate system.
As of now, i see most of the data is handled in Geographic Lat-Long coordinates.
or am i missing something?

Cheers,
kk

**Comment by aportagain** [comment]
@karunakar2 and I just had a quick chat offline, and we're hoping that his case can be described using the existing CF conventions around CRS descriptions & references: http://cfconventions.org/cf-conventions/cf-conventions.html#grid-mappings-and-projections in which case the resulting structure should be valid CF-JSON without further modification. Let me know how you get along, happy to help also if the CF bit turns out to be more complicated than expected :)

**Comment by aportagain** [comment]
Closing since I assume this can be dealt with by following CF, rather than requiring anything specific to CF-JSON.
